{
 "title": "TTS DIC QA - AI Chatbot Logs",
 "tags": [
  "TTS",
  "DIC",
  "QA",
  "AI-Chatbot",
  "Docker"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "log_level",
    "label": "Log Level",
    "query": "All : .*, ERROR : ERROR, WARN : WARN, INFO : INFO"
   },
   { "name": "search_text", "label": "Search Text" }
  ]
 },
 "panels": [
  {
   "title": "AI-CHATBOT - APP",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{project=\"AI-Chatbot\", service_type=\"app\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "AI-CHATBOT - WORKER-APPROVED-DOCS",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{project=\"AI-Chatbot\", service_type=\"worker-approved-docs\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "AI-CHATBOT - WORKER-UPLOAD-QUESTIONS",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{project=\"AI-Chatbot\", service_type=\"worker-upload-questions\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "AI-CHATBOT - POSTGRES",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{project=\"AI-Chatbot\", service_type=\"postgres\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "AI-CHATBOT - PROMPT-FAQ-UI",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "{project=\"AI-Chatbot\", service_type=\"prompt-faq-ui\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  }
 ]
}