{
 "title": "TTS DIC QA - IBPIS WithoutTrillex Logs",
 "tags": [
  "TTS",
  "DIC",
  "QA",
  "KSA",
  "IBPIS"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "log_level",
    "label": "Log Level",
    "query": "All : .*, ERROR : ERROR, WARN : WARN, INFO : INFO"
   },
   { "name": "search_text", "label": "Search Text" }
  ]
 },
 "panels": [
  {
   "title": "IBPIS WoT - TOMCAT",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{project=\"IBPIS_WithoutTrillex\", service_type=\"tomcat\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "IBPIS WoT - BULKPROCESSOR",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{project=\"IBPIS_WithoutTrillex\", service_type=\"BulkProcessor\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "IBPIS WoT - DIRECTUPLOAD",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{project=\"IBPIS_WithoutTrillex\", service_type=\"Directupload\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "IBPIS WoT - KAFKALISTENER",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{project=\"IBPIS_WithoutTrillex\", service_type=\"KafkaListener\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "IBPIS WoT - NOTIFICATIONS",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "{project=\"IBPIS_WithoutTrillex\", service_type=\"Notifications\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "IBPIS WoT - ONLINEDARGENERATOR",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "{project=\"IBPIS_WithoutTrillex\", service_type=\"OnlineDARGenerator\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "IBPIS WoT - PAYMENTRECON",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "{project=\"IBPIS_WithoutTrillex\", service_type=\"PaymentRecon\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "IBPIS WoT - PRELOAD",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "{project=\"IBPIS_WithoutTrillex\", service_type=\"Preload\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  }
 ]
}