{
 "title": "TTS DIC QA - IBP QA Logs",
 "tags": [
  "TTS",
  "DIC",
  "QA",
  "KSA",
  "IBP"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "log_level",
    "label": "Log Level",
    "query": "All : .*, ERROR : ERROR, WARN : WARN, INFO : INFO"
   },
   { "name": "search_text", "label": "Search Text" }
  ]
 },
 "panels": [
  {
   "title": "IBP QA - TOMCAT",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{project=\"IBP_QA\", service_type=\"tomcat\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "IBP QA - DIRECTUPLOAD",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{project=\"IBP_QA\", service_type=\"Directupload\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "IBP QA - EXPLICITPROCESSOR",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{project=\"IBP_QA\", service_type=\"ExplicitProcessor\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "IBP QA - FILESECURITYMOCKSCANNER",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "{project=\"IBP_QA\", service_type=\"FileSecurityMockScanner\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "IBP QA - FILESECURITYSCANWATCHER",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "{project=\"IBP_QA\", service_type=\"FileSecurityScanWatcher\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "IBP QA - ONLINEDARGENERATOR",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "{project=\"IBP_QA\", service_type=\"OnlineDARGenerator\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "IBP QA - REFUND",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "{project=\"IBP_QA\", service_type=\"Refund\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "IBP QA - EDAAFILEWATCHER",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 84 },
   "targets": [
    {
     "expr": "{project=\"IBP_QA\", service_type=\"EdaaFileWatcher\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "IBP QA - EDAAMAINPROCESS",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 96 },
   "targets": [
    {
     "expr": "{project=\"IBP_QA\", service_type=\"EdaaMainProcess\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "IBP QA - BGMESSAGEPROCESSOR",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 108 },
   "targets": [
    {
     "expr": "{project=\"IBP_QA\", service_type=\"BGMessageProcessor\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "IBP QA - BACKGROUNDTHREADPROCESSOR",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 120 },
   "targets": [
    {
     "expr": "{project=\"IBP_QA\", service_type=\"BackgroundThreadProcessor\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "IBP QA - NOTIFICATIONMESSAGEPROCESSOR",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 132 },
   "targets": [
    {
     "expr": "{project=\"IBP_QA\", service_type=\"NotificationMessageProcessor\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  }
 ]
}