{
 "title": "TTS DIC QA - BRHUB Logs",
 "tags": [
  "TTS",
  "DIC",
  "QA",
  "KSA",
  "BRHUB"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "log_level",
    "label": "Log Level",
    "query": "All : .*, ERROR : ERROR, WARN : WARN, INFO : INFO"
   },
   { "name": "search_text", "label": "Search Text" }
  ]
 },
 "panels": [
  {
   "title": "BRHUB - TOMCAT",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{project=\"BRHUB\", service_type=\"tomcat\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "BRHUB - BULKPROCESSOR",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{project=\"BRHUB\", service_type=\"BulkProcessor\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "BRHUB - DIRECTUPLOAD",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{project=\"BRHUB\", service_type=\"Directupload\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "BRHUB - KAFKALISTENER",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{project=\"BRHUB\", service_type=\"KafkaListener\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "BRHUB - NOTIFICATIONS",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "{project=\"BRHUB\", service_type=\"Notifications\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "BRHUB - ONLINEDARGENERATOR",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "{project=\"BRHUB\", service_type=\"OnlineDARGenerator\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "BRHUB - PAYMENTRECON",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "{project=\"BRHUB\", service_type=\"PaymentRecon\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "BRHUB - PRELOAD",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "{project=\"BRHUB\", service_type=\"Preload\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "BRHUB - REFUND",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "{project=\"BRHUB\", service_type=\"Refund\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "BRHUB - TTS-RE-SCRIPTS-BRHUB",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "{project=\"BRHUB\", service_type=\"TTS-RE-Scripts-BRHUB\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "BRHUB - AUDIT_LOGGING",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "{project=\"BRHUB\", service_type=\"audit_logging\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  }
 ]
}