{
 "title": "TTS DIC QA - ARC Logs",
 "tags": [
  "TTS",
  "DIC",
  "QA",
  "KSA",
  "ARC"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "log_level",
    "label": "Log Level",
    "query": "All : .*, ERROR : ERROR, WARN : WARN, INFO : INFO"
   },
   { "name": "search_text", "label": "Search Text" }
  ]
 },
 "panels": [
  {
   "title": "ARC - TOMCAT",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{project=\"ARC\", service_type=\"tomcat\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "ARC - ARCCLIENTMESSAGELISTENER",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{project=\"ARC\", service_type=\"ARCClientMessageListener\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "ARC - ARCCLIENTMESSAGELISTENERMOCK",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{project=\"ARC\", service_type=\"ARCClientMessageListenerMock\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "ARC - BULKPROCESSOR",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{project=\"ARC\", service_type=\"BulkProcessor\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "ARC - DIRECTUPLOAD",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "{project=\"ARC\", service_type=\"Directupload\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "ARC - KAFKALISTENER",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "{project=\"ARC\", service_type=\"KafkaListener\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "ARC - NOTIFICATIONS",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "{project=\"ARC\", service_type=\"Notifications\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "ARC - ONLINEDARGENERATOR",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "{project=\"ARC\", service_type=\"OnlineDARGenerator\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "ARC - PAYMENTRECON",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "{project=\"ARC\", service_type=\"PaymentRecon\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "ARC - PRELOAD",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "{project=\"ARC\", service_type=\"Preload\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "ARC - REFUND",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "{project=\"ARC\", service_type=\"Refund\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "ARC - UCMKAKFAMESSAGELISTENER",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "{project=\"ARC\", service_type=\"UCMKakfaMessageListener\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "ARC - SCRIPTS",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 96 },
   "targets": [
    {
     "expr": "{project=\"ARC\", service_type=\"scripts\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "ARC - SENDFIXMESSAGE",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 104 },
   "targets": [
    {
     "expr": "{project=\"ARC\", service_type=\"sendfixmessage\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  }
 ]
}