{
 "title": "TTS DIC QA - TTSRE Logs",
 "tags": [
  "TTS",
  "DIC",
  "QA",
  "KSA",
  "TTSRE"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "log_level",
    "label": "Log Level",
    "query": "All : .*, ERROR : ERROR, WARN : WARN, INFO : INFO"
   },
   { "name": "search_text", "label": "Search Text" }
  ]
 },
 "panels": [
  {
   "title": "TTSRE - TOMCAT",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{project=\"TTSRE\", service_type=\"tomcat\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "TTSRE - BULKPROCESSOR",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{project=\"TTSRE\", service_type=\"BulkProcessor\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "TTSRE - DATACLEANUPPROCESSOR",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{project=\"TTSRE\", service_type=\"DataCleanupProcessor\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "TTSRE - DIRECTUPLOAD",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{project=\"TTSRE\", service_type=\"Directupload\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "TTSRE - KAFKALISTENER1",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "{project=\"TTSRE\", service_type=\"KafkaListener1\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "TTSRE - NOTIFICATIONS",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "{project=\"TTSRE\", service_type=\"Notifications\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "TTSRE - ONLINEDARGENERATOR",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "{project=\"TTSRE\", service_type=\"OnlineDARGenerator\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "TTSRE - PAYMENTRECON",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "{project=\"TTSRE\", service_type=\"PaymentRecon\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "TTSRE - PRELOAD",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "{project=\"TTSRE\", service_type=\"Preload\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "TTSRE - SENDFIXMESSAGE",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "{project=\"TTSRE\", service_type=\"SendFixMessage\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "TTSRE - TTS-RE-SCRIPTS",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "{project=\"TTSRE\", service_type=\"TTS-RE-Scripts\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  }
 ]
}