{
 "title": "TTS DIC QA - IBPIS WithTrillex Logs",
 "tags": [
  "TTS",
  "DIC",
  "QA",
  "KSA",
  "IBPIS"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "log_level",
    "label": "Log Level",
    "query": "All : .*, ERROR : ERROR, WARN : WARN, INFO : INFO"
   },
   { "name": "search_text", "label": "Search Text" }
  ]
 },
 "panels": [
  {
   "title": "IBPIS WT - TOMCAT",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{project=\"IBPIS_WithTrillex\", service_type=\"tomcat\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "IBPIS WT - BOOKBULKDATAPROCESSOR",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{project=\"IBPIS_WithTrillex\", service_type=\"BOOKBulkDataProcessor\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "IBPIS WT - DIRECTUPLOADPOLLER",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{project=\"IBPIS_WithTrillex\", service_type=\"DirectUploadPoller\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "IBPIS WT - EXPLICITPROCESSOR",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{project=\"IBPIS_WithTrillex\", service_type=\"ExplicitProcessor\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "IBPIS WT - FILESECURITYMOCKSCANNER",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "{project=\"IBPIS_WithTrillex\", service_type=\"FileSecurityMockScanner\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "IBPIS WT - FILESECURITYSCANWATCHER",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "{project=\"IBPIS_WithTrillex\", service_type=\"FileSecurityScanWatcher\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "IBPIS WT - IMSMAILERTTSBOOK",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "{project=\"IBPIS_WithTrillex\", service_type=\"IMSMailerTTSBOOK\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "IBPIS WT - ONLINEREPORTGENERATOR",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "{project=\"IBPIS_WithTrillex\", service_type=\"OnlineReportGenerator\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "IBPIS WT - PAYMENTRECONCILIATION",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "{project=\"IBPIS_WithTrillex\", service_type=\"PaymentReconciliation\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "IBPIS WT - PROCESSPRELOADFILE",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "{project=\"IBPIS_WithTrillex\", service_type=\"ProcessPreloadFile\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "IBPIS WT - REFUNDREPORTGENERATOR",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "{project=\"IBPIS_WithTrillex\", service_type=\"RefundReportGenerator\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  }
 ]
}