{
 "title": "TTS DIC QA - ADXSIP Logs",
 "tags": [
  "TTS",
  "DIC",
  "QA",
  "UAE",
  "ADXSIP"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "log_level",
    "label": "Log Level",
    "query": "All : .*, ERROR : ERROR, WARN : WARN, INFO : INFO"
   },
   { "name": "search_text", "label": "Search Text" }
  ]
 },
 "panels": [
  {
   "title": "ADXSIP - NOTIFICATION PROCESS",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{project=\"ADXSIP\", service_type=\"Notification process\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "ADXSIP - APPLICATION",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{project=\"ADXSIP\", service_type=\"application\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "ADXSIP - APPLICATION_ERROR",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{project=\"ADXSIP\", service_type=\"application_error\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "ADXSIP-BO - APPLICATION",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "{project=\"ADXSIP\", service_type=\"bo_application\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "ADXSIP-BO - APPLICATION_ERROR",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "{project=\"ADXSIP\", service_type=\"bo_application_error\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "ADXSIP-SSPAPI - APPLICATION",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "{project=\"ADXSIP\", service_type=\"sspapi_application\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "ADXSIP-SSPAPI - APPLICATION_ERROR",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "{project=\"ADXSIP\", service_type=\"sspapi_application_error\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  }
 ]
}