{
 "title": "TTS DIC QA - TABADUL Logs",
 "tags": [
  "TTS",
  "DIC",
  "QA",
  "UAE",
  "TABADUL"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "log_level",
    "label": "Log Level",
    "query": "All : .*, ERROR : ERROR, WARN : WARN, INFO : INFO"
   },
   { "name": "search_text", "label": "Search Text" }
  ]
 },
 "panels": [
  {
   "title": "TABADUL - TOMCAT",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{project=\"TABADUL\", service_type=\"tomcat\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "TABADUL - LOAD BROKER LIST",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{project=\"TABADUL\", service_type=\"load_broker_list\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "TABADUL - SHAREINFO JOB",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{project=\"TABADUL\", service_type=\"shareinfo_job\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "TABADUL - OFFER PROCESS LISTENER",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "{project=\"TABADUL\", service_type=\"offer_process_listener\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  }
 ]
}