{
 "title": "TTS DIC QA - ADX SSP Node 2 Logs",
 "tags": [
  "TTS",
  "DIC",
  "QA",
  "UAE",
  "ADX_SSP"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "log_level",
    "label": "Log Level",
    "query": "All : .*, ERROR : ERROR, WARN : WARN, INFO : INFO"
   },
   { "name": "search_text", "label": "Search Text" }
  ]
 },
 "panels": [
  {
   "title": "SSP N2 - SSP-PROCESSOR",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{project=\"ADX_SSP_NODE_2\", service_type=\"ssp-processor\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "SSP N2 - ADMINNOTIFICATIONSENDERJOB",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{project=\"ADX_SSP_NODE_2\", service_type=\"AdminNotificationSenderJob\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "SSP N2 - CHECKANDRESETDDAREGISTRATIONSTATUSPROCESSORJOB",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{project=\"ADX_SSP_NODE_2\", service_type=\"CheckAndResetDDARegistrationStatusProcessorJob\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "SSP N2 - DDAPAYMENTPROCESSORJOB",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{project=\"ADX_SSP_NODE_2\", service_type=\"DDAPaymentProcessorJob\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "SSP N2 - DDAPAYMENTSTATUSPROCESSORJOB",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "{project=\"ADX_SSP_NODE_2\", service_type=\"DDAPaymentStatusProcessorJob\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "SSP N2 - DDAREGISTRATIONPROCESSORJOB",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "{project=\"ADX_SSP_NODE_2\", service_type=\"DDARegistrationProcessorJob\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "SSP N2 - IPIPAYMENTREQUESTPROCESSORJOB",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "{project=\"ADX_SSP_NODE_2\", service_type=\"IPIPaymentRequestProcessorJob\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "SSP N2 - IPIPAYMENTSTATUSPROCESSORJOB",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "{project=\"ADX_SSP_NODE_2\", service_type=\"IPIPaymentStatusProcessorJob\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "SSP N2 - LOADBROKERDATAJOB",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "{project=\"ADX_SSP_NODE_2\", service_type=\"LoadBrokerDataJob\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "SSP N2 - LOADINAVFEEDDATAJOB",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "{project=\"ADX_SSP_NODE_2\", service_type=\"LoadINAVFeedDataJob\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "SSP N2 - NOTIFICATIONSENDERJOB",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "{project=\"ADX_SSP_NODE_2\", service_type=\"NotificationSenderJob\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "SSP N2 - PAYMENTREMINDERNOTIFICATIONPROCESSORJOB",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "{project=\"ADX_SSP_NODE_2\", service_type=\"PaymentReminderNotificationProcessorJob\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  }
 ]
}