{
 "title": "TTS DIC QA - MBANK Logs",
 "tags": [
  "TTS",
  "DIC",
  "QA",
  "UAE",
  "MBANK"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "log_level",
    "label": "Log Level",
    "query": "All : .*, ERROR : ERROR, WARN : WARN, INFO : INFO"
   },
   { "name": "search_text", "label": "Search Text" }
  ]
 },
 "panels": [
  {
   "title": "MBANK - TOMCAT",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{project=\"MBANK\", service_type=\"tomcat\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "MBANK - OFFER PROCESS LISTENER",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{project=\"MBANK\", service_type=\"Offer Process Listener\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "MBANK - OFFER RECON LISTENER",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{project=\"MBANK\", service_type=\"Offer Recon Listener\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "MBANK - OFFEREMAILPROCESS",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{project=\"MBANK\", service_type=\"OfferEmailProcess\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "MBANK - OFFEREMAILPROCESS 2",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "{project=\"MBANK\", service_type=\"OfferEmailProcess 2\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  }
 ]
}