{
 "title": "TTS DIC QA - DFM Logs",
 "tags": [
  "TTS",
  "DIC",
  "QA",
  "UAE",
  "DFM"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "log_level",
    "label": "Log Level",
    "query": "All : .*, ERROR : ERROR, WARN : WARN, INFO : INFO"
   },
   { "name": "search_text", "label": "Search Text" }
  ]
 },
 "panels": [
  {
   "title": "DFM - TOMCAT",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{project=\"DFM\", service_type=\"tomcat\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "DFM - MEETING PROCESS",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{project=\"DFM\", service_type=\"Meeting Process\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "DFM - NOTIFICATION",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{project=\"DFM\", service_type=\"Notification\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "DFM - SMS EMAIL",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "{project=\"DFM\", service_type=\"SMS Email\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  }
 ]
}