{
 "title": "TTS DIC QA - MAR Logs",
 "tags": [
  "TTS",
  "DIC",
  "QA",
  "QATAR",
  "MAR"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "log_level",
    "label": "Log Level",
    "query": "All : .*, ERROR : ERROR, WARN : WARN, INFO : INFO, FATAL : FATAL, DEBUG : DEBUG"
   },
   { "name": "search_text", "label": "Search Text" }
  ]
 },
 "panels": [
  {
   "title": "MAR - TOMCAT",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{project=\"MAR\", app=\"MAR\", service_type=\"tomcat\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "MAR - TOMCAT ONLY",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{project=\"MAR\", app=\"MAR\", service_type=\"tomcat-only\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "MARRI - TOMCAT",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{project=\"MAR\", app=\"MARRI\", service_type=\"tomcat\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "MAR DASHBOARD - TOMCAT",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "{project=\"MAR\", app=\"MARDashBoard\", service_type=\"tomcat\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "QIBRI - TOMCAT",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "{project=\"MAR\", app=\"QIBRI\", service_type=\"tomcat\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "QIBRI - TOMCAT ONLY",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "{project=\"MAR\", app=\"QIBRI\", service_type=\"tomcat-only\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "QIBRI DASHBOARD - TOMCAT",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "{project=\"MAR\", app=\"QIBRIDashBoard\", service_type=\"tomcat\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  },
  {
   "title": "QIBRI DASHBOARD - TOMCAT ONLY",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 84 },
   "targets": [
    {
     "expr": "{project=\"MAR\", app=\"QIBRIDashBoard\", service_type=\"tomcat-only\"} |~ \"$log_level\" |= \"$search_text\""
    }
   ]
  }
 ]
}